# Generated by Django 4.2.5 on 2023-10-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='sobrenome',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
