# Generated by Django 4.2.5 on 2023-10-01 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuarios_email_alter_usuarios_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='permissao',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
