# Generated by Django 4.2.5 on 2023-10-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuarios_permissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='permissao',
            field=models.CharField(max_length=30),
        ),
    ]
