# Generated by Django 4.2.5 on 2023-10-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_usuarios_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='permissao',
            field=models.TextField(max_length=30),
        ),
    ]
