# Generated by Django 4.2.5 on 2023-10-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usuarios_permissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='permissao',
        ),
    ]
