# Generated by Django 4.2.5 on 2023-10-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_usuarios_permissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='sobrenome',
        ),
    ]
