# Generated by Django 4.2.5 on 2023-10-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cliente_delete_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
                ('estoque', models.IntegerField()),
                ('minimo', models.IntegerField()),
                ('custo', models.FloatField()),
                ('valor', models.FloatField()),
            ],
        ),
    ]
